name: "Package addon"

on:
  push:
    tags:
    - 'v*'

env:
  PROJECT_PATH: 'SAPB1-CICD/SAPB1-CICD.csproj'
  TARGET_PATH: ${{ github.workspace }}\SAPB1-CICD\bin\Release\SAPB1-CICD.exe
  SOLUTION_DIR: ${{ github.workspace }}\SAPB1-CICD
  PROJECT_NAME: 'SAPB1-CICD'
  OUTPUT_DIR: ${{ github.workspace }}\output

jobs:
  deploy:
    name: 'Package addon'
    runs-on: 'windows-latest'

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    
    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE

    - name: Create Build Directory
      run: mkdir _build
      
    - name: Restore Packages
      run: nuget restore SAPB1-CICD.sln

    - name: Build Solution
      run: |
        msbuild.exe SAPB1-CICD.sln /nologo /nr:false /p:platform="Any CPU" /p:configuration="Release"
    
    - name: Pakcage Addon
      run: ExtensionPackage/ExtensionPackage.exe /v:"0.06" /86:"${{ env.PROJECT_PATH }}" /64:"${{ env.PROJECT_PATH }}" /p:"${{ env.OUTPUT_DIR }}\${{ env.PROJECT_NAME }}.zip" /s:"${{ env.SOLUTION_DIR }}\SAPB1-CICD.ard" /ex:".pdb"
  