name: "Package addon"

on:
  push:
    tags:
    - 'v*'

env:
  PROJECT_PATH: 'SAPB1-CICD/SAPB1-CICD.csproj'
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}\output

jobs:
  deploy:
    name: 'Package addon'
    runs-on: 'windows-latest'
    
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    
    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE

    - name: Create Build Directory
      run: mkdir _build
      
    - name: Restore Packages
      run: nuget restore SAPB1-CICD.sln

    - name: Build Solution
      run: |
        msbuild.exe SAPB1-CICD.sln /nologo /nr:false /p:platform="Any CPU" /p:configuration="Release"
        
  